import { UpgradeConfig } from './types';

export const UPGRADES: UpgradeConfig[] = [

  // ── Ère Sauvage (age 0) ─────────────────────────────────────────────────────
  {
    id: 'monkey',
    name: 'Singe',
    image: require('@/assets/images/upgrades/age-0/singe.png'),
    description: 'Ramasse des bananes pour vous',
    baseCost: 10,
    baseBps: 0.1,
    maxCount: 100,
  },
  {
    id: 'guerrier_massai',
    name: 'Guerrier Maasaï',
    image: require('@/assets/images/upgrades/age-0/guerrier_massai_banana.png'),
    description: 'Garde et récolte les bananes',
    baseCost: 50,
    baseBps: 0.5,
    unlockedBy: 'buy_10_monkeys',
    maxCount: 100,
  },
  {
    id: 'bananier',
    name: 'Bananier',
    image: require('@/assets/images/upgrades/age-0/bananier_banana_clicker.png'),
    description: 'Pousse et produit des bananes en continu',
    baseCost: 250,
    baseBps: 2,
    unlockedBy: 'buy_5_guerriers',
    maxCount: 50,
  },
  {
    id: 'girafe',
    name: 'Girafe Cueilleuse',
    image: require('@/assets/images/upgrades/age-0/girafe_cueilleuse.png'),
    description: 'Cueille les bananes en hauteur, là où personne ne peut aller',
    baseCost: 1000,
    baseBps: 7,
    unlockedBy: 'buy_3_bananiers',
    maxCount: 25,
  },

  // ── Ère Agricole (age 1) ─────────────────────────────────────────────────────
  {
    id: 'paysan',
    name: 'Paysan',
    image: require('@/assets/images/upgrades/age-1/paysan.png'),
    description: 'Cultive des bananes sur ses terres',
    baseCost: 75,
    baseBps: 8,
    minAge: 1,
    maxCount: 100,
  },
  {
    id: 'charrue',
    name: 'Charrue',
    image: require('@/assets/images/upgrades/age-1/charrue.png'),
    description: 'Retourne la terre pour de meilleures récoltes',
    baseCost: 400,
    baseBps: 25,
    minAge: 1,
    unlockedBy: 'buy_10_paysans',
    maxCount: 75,
  },
  {
    id: 'moulin',
    name: 'Moulin à Vent',
    image: require('@/assets/images/upgrades/age-1/moulin_a_vent.png'),
    description: 'Transforme le blé en farine de banane',
    baseCost: 1500,
    baseBps: 80,
    minAge: 1,
    unlockedBy: 'buy_5_charrues',
    maxCount: 50,
  },
  {
    id: 'marche',
    name: 'Marché',
    image: require('@/assets/images/upgrades/age-1/marche.png'),
    description: 'Commerce les bananes dans toute la région',
    baseCost: 6000,
    baseBps: 250,
    minAge: 1,
    unlockedBy: 'buy_3_moulins',
    maxCount: 25,
  },

  // ── Ère Industrielle (age 2) ─────────────────────────────────────────────────
  {
    id: 'ouvrier',
    name: 'Ouvrier',
    image: require('@/assets/images/upgrades/age-2/ouvrier.png'),
    description: 'Travaille à la chaîne pour produire des bananes',
    baseCost: 15000,
    baseBps: 600,
    minAge: 2,
    maxCount: 100,
  },
  {
    id: 'machine_vapeur',
    name: 'Machine à Vapeur',
    image: require('@/assets/images/upgrades/age-2/machine_vapeur.png'),
    description: 'La révolution industrielle au service des bananes',
    baseCost: 60000,
    baseBps: 2000,
    minAge: 2,
    unlockedBy: 'buy_10_ouvriers',
    maxCount: 75,
  },
  {
    id: 'usine',
    name: 'Usine',
    image: require('@/assets/images/upgrades/age-2/usine.png'),
    description: 'Produit des bananes à grande échelle',
    baseCost: 250000,
    baseBps: 7000,
    minAge: 2,
    unlockedBy: 'buy_5_machines',
    maxCount: 50,
  },
  {
    id: 'locomotive',
    name: 'Locomotive',
    image: require('@/assets/images/upgrades/age-2/locomotive.png'),
    description: 'Transporte et distribue les bananes partout',
    baseCost: 1000000,
    baseBps: 25000,
    minAge: 2,
    unlockedBy: 'buy_3_usines',
    maxCount: 25,
  },

  // ── Ère Moderne (age 3) ──────────────────────────────────────────────────────
  {
    id: 'ingenieur',
    name: 'Ingénieur',
    image: require('@/assets/images/upgrades/age-3/ingenieur.png'),
    description: 'Optimise chaque étape de la production bananière',
    baseCost: 100000,
    baseBps: 60000,
    minAge: 3,
    maxCount: 100,
  },
  {
    id: 'ordinateur',
    name: 'Ordinateur',
    image: require('@/assets/images/upgrades/age-3/ordinateur.png'),
    description: 'Calcule le chemin optimal pour chaque banane',
    baseCost: 500000,
    baseBps: 200000,
    minAge: 3,
    unlockedBy: 'buy_10_ingenieurs',
    maxCount: 75,
  },
  {
    id: 'drone',
    name: 'Drone',
    image: require('@/assets/images/upgrades/age-3/drone.png'),
    description: 'Livre les bananes en temps réel depuis les airs',
    baseCost: 2000000,
    baseBps: 700000,
    minAge: 3,
    unlockedBy: 'buy_5_ordinateurs',
    maxCount: 50,
  },
  {
    id: 'satellite',
    name: 'Satellite',
    image: require('@/assets/images/upgrades/age-3/satellite.png'),
    description: "Surveille et gère les plantations depuis l'orbite",
    baseCost: 8000000,
    baseBps: 2500000,
    minAge: 3,
    unlockedBy: 'buy_3_drones',
    maxCount: 25,
  },

  // ── Ère Robotique (age 4) ────────────────────────────────────────────────────
  {
    id: 'robot',
    name: 'Robot',
    image: require('@/assets/images/upgrades/age-4/robot.png'),
    description: 'Récolte sans relâche, 24h/24',
    baseCost: 400000000,
    baseBps: 8000000,
    minAge: 4,
    maxCount: 100,
  },
  {
    id: 'ia',
    name: 'Intelligence Artificielle',
    image: require('@/assets/images/upgrades/age-4/ia.png'),
    description: 'Prédit et optimise chaque récolte à la milliseconde',
    baseCost: 1500000000,
    baseBps: 30000000,
    minAge: 4,
    unlockedBy: 'buy_10_robots',
    maxCount: 75,
  },
  {
    id: 'megastructure',
    name: 'Mégastructure',
    image: require('@/assets/images/upgrades/age-4/megastructure.png'),
    description: 'Une sphère de Dyson entièrement dédiée aux bananes',
    baseCost: 7000000000,
    baseBps: 150000000,
    minAge: 4,
    unlockedBy: 'buy_5_ia',
    maxCount: 50,
  },
];
